# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Step 1: Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Step 2: Load the data
# Let's assume your hiring.csv file is available in the same directory as this script
data = pd.read_csv('/content/hiring.csv')

# Step 3: Inspect the data
print(data.head())


# Step 6: Initialize the model
model = LinearRegression()

# Step 7: Train the model
model.fit(X_train, y_train)

# Step 8: Evaluate the model
y_pred = model.predict(X_test)
print(f'Mean Squared Error: {mean_squared_error(y_test, y_pred)}')

# Step 9: Predict salaries for the new candidates
new_candidates = pd.DataFrame({
    'Experience': [2, 12],
    'Test Score': [9, 10],
    'Interview Score': [6, 10]
})

predicted_salaries = model.predict(new_candidates)
print(f'Predicted Salaries: {predicted_salaries}')

import pandas as pd

# Load the Canada data
data = pd.read_csv('/content/canada_per_capita_income.csv')  # Replace with the actual file path

# Check the first few rows to understand the data structure
print(data.head())

# Check column names to make sure we have 'year' and 'per capita income' columns
print(data.columns)
# Clean the column names
data.columns = data.columns.str.strip()

# Check the cleaned columns
print(data.columns)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

# Select the features and target
X = data[['year']]  # Features (year)
y = data['per capita income (US$)']  # Target (per capita income)

# Step 4: Train the Linear Regression Model
model = LinearRegression()
model.fit(X, y)

# Step 5: Predict the per capita income for the year 2020
year_2020 = np.array([[2020]])  # Year to predict for
predicted_income_2020 = model.predict(year_2020)

print(f'Predicted per capita income for Canada in 2020: ${predicted_income_2020[0]:,.2f}')